export {default as HomeIcon} from "./svgs/home.svg"
export {default as BookIcon} from "./svgs/book.svg"
export {default as CalendarIcon} from "./svgs/calendar.svg"
export {default as UserIcon} from "./svgs/user.svg"
export {default as MenuIcon} from "./svgs/menu.svg"
export {default as ChevronDownIcon} from "./svgs/chevronDown.svg"
export {default as ChevronUpIcon} from "./svgs/chevUp.svg"